### PR TITLE
[FIX] Changed API Url for the rulemanager

### PR DESCRIPTION
**Pull request by PietroG93**
Changed API Url for the rulemanager

new api url: https://rm-middleware-api.dev-digital-enabler.eng.it/api/v1

### CODE REVIEW

**Review by AleLuc98 — APPROVED** [review]

**Comment by robraccu** [comment]
@PietroG93 @Dnikodij ....too many branches guys...please align them

**Comment by PietroG93** [comment]
> @PietroG93 @Dnikodij ....too many branches guys...please align them

Which branches?

**Comment by robraccu** [comment]
> > @PietroG93 @Dnikodij ....too many branches guys...please align them
> 
> Which branches?

There are 2 other branches than main on UI-Configs and both are not aligned with main

**Review by robraccu — APPROVED** [review]

**Comment by Dnikodij** [comment]
> @PietroG93 @Dnikodij ....too many branches guys...please align them

i aligned them

**Pull request merged**
